---
controller:
  config:
    compute-full-forwarded-for: "true"
    use-forwarded-headers: "true"
    proxy-body-size: "0"    
  replicaCount: 1
  admissionWebhooks:
    enabled: true
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb